export const FETCH_ICECREAMS_REQUEST = 'FETCH_ICECREAMS_REQUEST'
export const FETCH_ICECREAMS_SUCCESS = 'FETCH_ICECREAMS_SUCCESS'
export const FETCH_ICECREAMS_FAILURE = 'FETCH_ICECREAMS_FAILURE'

export const DELETE_ICECREAMS = 'DELETE_ICECREAMS'

export const ADD_ICECREAMS_REQUEST = 'ADD_ICECREAMS_REQUEST'
export const ADD_ICECREAMS_SUCCESS = 'ADD_ICECREAMS_SUCCESS'
export const ADD_ICECREAMS_FAILURE = 'ADD_ICECREAMS_FAILURE'