export const ADD_CAKES_REQUEST = 'ADD_CAKES_REQUEST'
export const ADD_CAKES_SUCCESS = 'ADD_CAKES_SUCCESS'
export const ADD_CAKES_FAILURE = 'ADD_CAKES_FAILURE'

export const FETCH_CAKES_REQUEST = 'FETCH_CAKES_REQUEST'
export const FETCH_CAKES_SUCCESS = 'FETCH_CAKES_SUCCESS'
export const FETCH_CAKES_FAILURE = 'FETCH_CAKES_FAILURE'

export const DELETE_CAKES_SUCCESS = 'DELETE_CAKES_SUCCESS'